mac:

	g++ -c ../bin/atrr2.cpp
	g++ -c ../bin/atrrfunc.cpp
	g++ -c ../bin/filelib.cpp
	g++ -o atrr atrr2.o atrrfunc.o filelib.o

linux:

	g++ Semi_Menu_Window.cpp  -o ATRLinux -I include -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf
	g++ ATRLOCK.cpp -o ATRLOCK 
	g++ TriangleTest5.cpp -o animation -I include -lSDL2 


installMac:
	brew install sdl2
	brew install sdl2_image
	brew install sdl2_mixer
	brew install sdl2_ttf

installLinux:
	sudo apt-get install libsdl2-dev
	sudo apt-get install libsdl2-image-dev
	sudo apt-get install libsdl2-mixer-dev
	sudo apt-get install libsdl2-ttf-dev

clean:
	rm ATRmac
	rm animation
